<a href="https://colab.research.google.com/github/nayelimolar/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy es una libreria de Python.
NumPy se utiliza para trabajar con matrices o arreglo
NumPy es la abrebiatura de "Python numerico"
Tambien tiene funciones para trabajar en el dominio del algebra lineal, la transformada y las matrices
En Python tenemos listas que sirven como matrices pero son lentas de procesar.
NumPy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las lisas tradicionales.


In [2]:
#Primero tenemos que importar la libreria
import numpy

arreglo=numpy.array([1,2,3,4,5])
print(arreglo)


[1 2 3 4 5]


NumPy como np
NumPy generalmente es importa bajo el aliasnp. En Python los alias son un nombre alternativo para referirse a la misma cosa

In [3]:
import numpy as np

arreglo=np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


Comprobando la version de NumPy
La cadebna de la version de almacena en el atributo__version__

In [4]:
import numpy as np

print(np.__version__)

2.0.2


NumPy creando matrices
Crear un objetondarray de NumPy
NumPy se utiliza para trabajar con matrices. El objeto de matriz se llama ndarray.
Podemos crear un NumPy ndarray utilizando la funcion array()

In [5]:
import numpy as np

arreglo=np.array(["raul", "ana", "kimberly", "yazmin"])
print(arreglo)
print(type(arreglo))

['raul' 'ana' 'kimberly' 'yazmin']
<class 'numpy.ndarray'>


Dimensiones en matrices
Una dimension en matrices es un nivel de profundidad de matriz (matrices anidadas)
Una matriz anidada contiene matrices como alementos
Matrices 0-D. Son elemtos de una matriz. Cada valor de una matriz es una matriz 0-D. Ejemplo:Crea una matriz 0-D con un valor de 42

In [6]:
import numpy as np

arreglo=np.array(42)

print(arreglo)

42


Matrices 1-D que tiene matriices como 0-D como elementos se denomina matriz unidimensional o 1-D.
Estas son las matrices mas comunes y basicas.
Ejemplo: Crea una matrices de una dimension que tenga los valores 1,2,3,4,5

In [8]:
import  numpy as np

arreglo=np.array([1,2,3,4,5])

print(arreglo)

[1 2 3 4 5]


Matrices 2D
Una matriz que tiene matrices 1-D como elementos se denomina matriz 2-D.
A menudo se utiliza para representar matrices de sgundo orden. NumPy tiene un submodulo completo dedecado a operaciones como matrices llamado numpy.
mat.
Ejemplo:crea una matriz 2D que contenga dos matrices con los valores 123 y 456

In [9]:
import numpy as np

arreglo=np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
Una matriz que tiene matrices 2D se denomina matriz 3D.
Estas matrices se utilizan para representar una matriz de tercer orden.
Ejemplo:crea una mtiz 3D con 2 mnatrices bidimensionales, ambas conteniendo dos matrices con los valores 1,2,3 y 4,5,6.

In [10]:
import numpy as np

arreglo=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
