<a href="https://colab.research.google.com/github/nayelimolar/unidad1/blob/main/practica7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nayeli Molar Gutierrez- Practica 7- 25 de septiembre 2025
---------------------------------
Slicing Numpy
----------
Utiliza STEP para determinar el paso del corte:
Ejemplo:([1,2,3,4,5,6,7])- Devuelve todos
Los elementos del indice 1 al indice 5

In [5]:
import numpy as np

arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[1:5:2])

[2 4]


Ejemplo2: ([1,2,3,4,5,6,7])
devuelve los elementos de la matriz

In [4]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[::2])

[1 3 5 7]


Slice de matrices 2D
-------------------------
Ejemplo3:([[1,2,3,4,5],[6,7,8,9,19])
Del segundo elemento, corte del indice 1 al inidce 4

In [8]:
import numpy as np
arreglo=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[1, 1:4])


[7 8 9]


Ejemplo 4: ([[1,2,3,4,5],[6,7,8,9,10]])
De ambos elementos, devuelva el inice 1
---------------------------------------


In [9]:
import numpy as np
arreglo=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2, 2])

[3 8]


Ejemplo 5: ([[1,2,3,4,5],[6,7,8,9,10])
De ambos elementos corta el indice 1 al indice 4
-----------------------------------------

In [12]:
import numpy as np
arreglo=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


Ejercicio1- Autonomo
Del siguiente arreglo , ¿cual es el resultado?
([1,2,3,4,5,6,7])
corta del 1er elemento al 6to elemento con paso 2

In [17]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[0:6:2])

[1 3 5]
