<a href="https://colab.research.google.com/github/nayelimolar/unidad1/blob/main/Practica_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nayeli molar gutierrez-24 de septiembre de 2025
Practica 6- Cortar Arreglos Numpy
----------------------------------------------
Slice en Python significa tomar elementos de un indice determinado a otro determinado indice.

pasamos Slice en lugar del indice de esta manera: [star:end]
Sino pasamos el inicio se considera 0
Sino pasamos el final, su longiitud es considerada una matriz de una dimension
-----------------------------------------------
Ejemplo:([1,2,3,4,5,6,7])
Cortar los elementos del indice 1 al indice 5
--------------------------------------

In [1]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,6])

print(arreglo[1:5])

[2 3 4 5]


Ejemplo 2:
([1,2,3,4,5,6,7])
Cortar del indice 4 hasta el final de la matriz
-----------------------------------


In [2]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])

print(arreglo[4:])

[5 6 7]


Ejemplo 3:
([1,2,3,4,5,6,7])
Cortar elementos desde el principio hasta el indice 5

In [3]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])
print(arreglo[:5])

[1 2 3 4 5]


Ejemplo 4:
([1,2,3,4,5,6,7])
Corte negativo. Utilizamos el operador "menos" para hacer referencia a un indice desde el final.
--------------------------
Cortar del indice 3 desde el final al indice 1 desde el final

In [4]:
import numpy as np
arreglo=np.array([1,2,3,4,5,6,7])

print(arreglo[-3: -1])

[5 6]
